# Functions to log different components of the SLAM system to rerun:

import rerun as rr
import numpy as np

def log_camera(entity_path, world_T_cam_44, K_44):
    """Logs camera intrinsics and extrinsics to rerun."""

    assert world_T_cam_44.shape == (4, 4)
    assert K_44.shape == (4, 4)

    # Convert and log camera parameters
    Rot, trans = world_T_cam_44[:3, :3], world_T_cam_44[:3, 3]
    K_33 = K_44[:3, :3]

    rr.log(
        entity_path,
        rr.Pinhole(
            image_from_camera=K_33,
            width=K_33[0, 2] * 2,  # Assuming principal point is in the center
            height=K_33[1, 2] * 2,
        ),
    )

    rr.log(entity_path, rr.Transform3D(translation=trans, mat3x3=Rot))


def log_image(image):
    """Logs an image to rerun."""
    rr.log(f"image", rr.Image(image))


def log_local_map(frame_id, entity_path, points):  # Added 'points' parameter
    """Logs the local map to rerun."""
    # points = get_local_map(frame_id)  # Removed the call to get_local_map
    rr.log(f"{entity_path}/local_map", rr.Points3D(points))


def log_global_map(frame_id, entity_path, points):  # Added 'points' parameter
    """Logs the global map to rerun."""
    # points = get_global_map(frame_id)  # Removed the call to get_global_map
    rr.log(f"{entity_path}/global_map", rr.Points3D(points))


def log_key_frames(frame_id, entity_path, key_frames):  # Added 'key_frames' parameter
    """Logs the set of key frames to rerun."""
    # key_frames = get_key_frames(frame_id)  # Removed the call to get_key_frames
    for i, frame in enumerate(key_frames):
        # Assuming frame is a dictionary with "image" and "pose"
        image = frame["image"]
        world_T_cam_44 = frame["pose"]  # 4x4 transformation matrix
        K_44 = frame["K"]  # 4x4 intrinsic matrix
        frame_path = f"{entity_path}/key_frames/{i}"
        log_camera(frame_path, world_T_cam_44, K_44)
        log_image(frame_path, image)


def log_current_frame(frame_id, entity_path, image):  # Added 'image' parameter
    """Logs the current frame to rerun."""
    # image = get_current_frame(frame_id)  # Removed the call to get_current_frame
    rr.log(f"{entity_path}/current_frame", rr.Image(image))


def log_features(frame_id, entity_path, features):  # Added 'features' parameter
    """Logs features in the current frame."""
    # features = get_features(frame_id)  # Removed the call to get_features
    rr.log(f"{entity_path}/current_frame/features", rr.Points2D(features))


def log_dynamic_features(
    frame_id, entity_path, dynamic_features
):  # Added 'dynamic_features' parameter
    """Logs dynamic features in the current frame."""
    # dynamic_features = get_dynamic_features(frame_id)  # Removed the call to get_dynamic_features
    rr.log(
        f"{entity_path}/current_frame/dynamic_features",
        rr.Points2D(dynamic_features, color=(255, 0, 0)),
    )  # Visualize in red


def log_camera_path(frame_id, entity_path, camera_path):  # Added 'camera_path' parameter
    """Logs the camera path up to the current frame_id."""
    # camera_path = get_camera_path(frame_id)  # Removed the call to get_camera_path
    rr.log(f"{entity_path}/camera_path", rr.LineStrips3D([camera_path]))


def log_sam_masks(frame_id, entity_path, masks):  # Added 'masks' parameter
    """Logs the semantic masks generated by SAM."""
    # masks = get_sam_masks(frame_id)  # Removed the call to get_sam_masks
    for i, mask in enumerate(masks):
        rr.log(f"{entity_path}/sam_masks/{i}", rr.SegmentationImage(mask))


def log_sam_prompts(frame_id, entity_path, prompts):  # Added 'prompts' parameter
    """Logs the prompts given to SAM."""
    # prompts = get_sam_prompts(frame_id)  # Removed the call to get_sam_prompts
    rr.log(
        f"{entity_path}/sam_prompts", rr.Points2D(prompts, color=(0, 0, 255))
    )  # Visualize in blue


def log_frame_points(frame_id, entity_path, frame, colors=None, accumulate=False):
    """
    Logs the map points visible in the current frame as 3d point cloud.
    
    Parameters:
    -----------
    frame_id : int
        The ID of the current frame
    entity_path : str
        Base path for the entity in the visualization
    frame : Frame
        The frame object containing the points
    colors : np.ndarray, optional
        Custom colors for the points
    accumulate : bool, default=False
        If True, accumulate points from all frames. If False, only show current frame.
    """
    if frame is None:
        return
    
    # Get all points from the frame that are not None (matched map points)
    with frame._lock_features:
        matched_points = [p for p in frame.points if p is not None]
    
    if not matched_points:
        # No points to log
        return
    
    # Extract 3D positions and colors
    points_3d = np.array([p.pt for p in matched_points])
    
    if colors is None:
        # Use the colors stored in the map points
        point_colors = np.array([p.color for p in matched_points]) / 255.0
    else:
        point_colors = colors
    
    # Determine the entity path based on accumulation mode
    if accumulate == True:
        # Use frame-specific path to accumulate all frames
        point_path = f"{entity_path}/frame_{frame_id}/map_points"
    else:
        # Use a consistent path so new frames replace old ones
        point_path = f"{entity_path}/current_map_points"
    
    # Log the points to rerun
    rr.log(point_path, rr.Points3D(points_3d, colors=point_colors))
    
    return points_3d, point_colors


# def log_keyframes(kfs):
#     """ 
#     Input = List of keyframedata objects
#     Outpt = log all the images and masks of the keyframes for every timestamp
#     """
#     for i, kf in enumerate(kfs):
#         # Assuming kf is a KeyFrameData object with attributes 'img' and 'mask'
#         print("type of image, mask", type(kf.img), type(kf.dynamic_mask))
#         image = kf.img
#         mask = kf.dynamic_mask  # Assuming this is the mask you want to log
#         timestamp = kf.timestamp
        
#         # Log the image and mask
#         rr.log(f"keyframes/{timestamp}/image", rr.Image(image))
#         rr.log(f"keyframes/{timestamp}/mask", rr.Image(mask))


def log_keyframes_poses(kfs):
    """ 
    Input = List of KeyFrameData objects
    Output = Logs the poses of keyframes, also add image to the view. it should be a camera view with image - typical rerun viz
    """
    if not kfs:
        return
    
    import numpy as np
    import rerun as rr
    
    # Log each keyframe as a camera with its image
    for i, kf in enumerate(kfs):
        # Extract pose information (Tcw is camera-to-world transform)
        Rcw = kf.Rcw  # Rotation matrix
        tcw = kf.tcw  # Translation vector

        Hcw = np.eye(4)
        Hcw[:3, :3] = Rcw
        Hcw[:3, 3] = tcw
        # Convert to world-to-camera transform
        Hwc = np.linalg.inv(Hcw)
        # Convert to 3x3 rotation matrix and 3D translation vector
        Rwc = Hwc[:3, :3]
        twc = Hwc[:3, 3]
        # Temporarily calling Rcw as Rwc and tcw as twc for testing viz
        Rcw = Rwc
        tcw = twc
        
        # Create entity path
        entity_path = f"keyframes/poses/{kf.id}"
        
        # Create camera intrinsic matrix (assuming a pinhole camera model)
        if hasattr(kf.camera, 'K'):
            K = kf.camera.K
            
            # Get image dimensions
            width = kf.img.shape[1] if isinstance(kf.img, np.ndarray) else kf.img.width
            height = kf.img.shape[0] if isinstance(kf.img, np.ndarray) else kf.img.height
            
            # Extract focal length and principal point from K matrix
            fx = K[0, 0]
            fy = K[1, 1]
            cx = K[0, 2]
            cy = K[1, 2]
            
            # Log camera intrinsics
            rr.log(
                f"{entity_path}/image",
                rr.Pinhole(
                    resolution=[width, height],
                    focal_length=[fx, fy],
                    principal_point=[cx, cy]
                )
            )
        else:
            # Fallback if no calibration matrix is available
            width = kf.img.shape[1] if isinstance(kf.img, np.ndarray) else kf.img.width
            height = kf.img.shape[0] if isinstance(kf.img, np.ndarray) else kf.img.height
            
            rr.log(
                f"{entity_path}/image",
                rr.Pinhole(
                    resolution=[width, height],
                )
            )
        
        # Log the image
        if kf.img is not None:
            rr.log(f"{entity_path}/image/rgb", rr.Image(kf.img))
        
        # Log the camera pose
        rr.log(
            entity_path,
            rr.Transform3D(
                translation=tcw,
                mat3x3=Rcw,
            ),
        )
        
        # # Log frame ID as text
        # rr.log(
        #     f"{entity_path}/label",
        #     rr.TextAnnotation(
        #         text=f"KF {kf.id}",
        #         size=16,
        #         background_color=(0, 0, 0, 128),  # Semi-transparent black background
        #         text_color=(255, 255, 255, 255),  # White text
        #     ),
        # )
        
        # For visualization purposes, also log a point at the camera position
        rr.log(
            f"{entity_path}/position",
            rr.Points3D(
                positions=[-tcw],  # Negative of tcw is the camera position in world frame
                colors=[(0, 255, 0)],  # Green point
                radii=[0.005],  # Small point
            ),
        )
        
        # If there's a dynamic mask, log it too
        if hasattr(kf, 'dynamic_mask') and kf.dynamic_mask is not None:
            rr.log(f"{entity_path}/image/mask", rr.Image(kf.dynamic_mask))


def log_keyframes(kfs):
    """ 
    Input = List of KeyFrameData objects
    Output = Logs two concatenated images: one for all images and one for all masks,
             with numbered labels showing kf id, max 5 items per row
    """
    if not kfs:
        return
    
    import numpy as np
    from PIL import Image, ImageDraw, ImageFont
    
    # Get dimensions from first image (assuming all images have same size)
    sample_img = kfs[0].img
    if isinstance(sample_img, np.ndarray):
        height, width = sample_img.shape[:2]
    else:
        height, width = sample_img.size
    
    # Calculate grid dimensions
    n_items = len(kfs)
    items_per_row = min(5, n_items)  # Max 5 items per row
    n_rows = (n_items + items_per_row - 1) // items_per_row  # Ceiling division
    
    # Create blank canvases for composite images
    total_width = width * items_per_row
    total_height = height * n_rows
    composite_img = Image.new('RGB', (total_width, total_height), (255, 255, 255))
    composite_mask = Image.new('RGB', (total_width, total_height), (255, 255, 255))
    
    # Try to load a font, fall back to default if not available
    try:
        font = ImageFont.truetype("arial.ttf", 20)
    except:
        font = ImageFont.load_default()
    
    # Fill the composite images
    for i, kf in enumerate(kfs):
        # Calculate position in grid
        row = i // items_per_row
        col = i % items_per_row
        x = col * width
        y = row * height
        
        # Convert images if necessary and paste them
        img = kf.img
        mask = kf.dynamic_mask
        print("Shape of mask to be logged", mask.shape)
        if isinstance(img, np.ndarray):
            img = Image.fromarray(img)
        if isinstance(mask, np.ndarray):
            mask = Image.fromarray(mask)
            
        composite_img.paste(img, (x, y))
        composite_mask.paste(mask, (x, y))
        
        # Add number label
        draw_img = ImageDraw.Draw(composite_img)
        draw_mask = ImageDraw.Draw(composite_mask)
        label = str(i)
        draw_img.text((x + 5, y + 5), label, fill=(255, 0, 0), font=font)  # Red text for image
        draw_mask.text((x + 5, y + 5), label, fill=(255, 0, 0), font=font)  # Red text for mask
    
    # Convert to numpy arrays for logging
    composite_img_array = np.array(composite_img)
    composite_mask_array = np.array(composite_mask)
    
    # Log the composite images
    rr.log("keyframes/composite/image", rr.Image(composite_img_array))
    rr.log("keyframes/composite/mask", rr.Image(composite_mask_array))

def log_all(
    frame_id,
    entity_path="world",
    # Add parameters for all the data you want to log
    local_map_points=None,
    global_map_points=None,
    key_frames=None,
    current_frame_image=None,
    features=None,
    dynamic_features=None,
    camera_path=None,
    sam_masks=None,
    sam_prompts=None,
    current_frame=None,  # Added parameter for the current frame
    accumulate_frame_points=False,  # New parameter to control point accumulation
):
    """Logs all the components of the SLAM system to rerun."""

    rr.set_time_sequence("frame", frame_id)

    # Add toggle for each logging component as needed
    if local_map_points is not None:
        log_local_map(frame_id, entity_path, local_map_points)
    if global_map_points is not None:
        log_global_map(frame_id, entity_path, global_map_points)
    if key_frames is not None:
        log_key_frames(frame_id, entity_path, key_frames)
    if current_frame_image is not None:
        log_current_frame(frame_id, entity_path, current_frame_image)
    if features is not None:
        log_features(frame_id, entity_path, features)
    if dynamic_features is not None:
        log_dynamic_features(frame_id, entity_path, dynamic_features)
    if camera_path is not None:
        log_camera_path(frame_id, entity_path, camera_path)
    if sam_masks is not None:
        log_sam_masks(frame_id, entity_path, sam_masks)
    if sam_prompts is not None:
        log_sam_prompts(frame_id, entity_path, sam_prompts)
    if current_frame is not None:
        log_frame_points(frame_id, entity_path, current_frame, accumulate=accumulate_frame_points)